name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [texlive, texlive-full, xetexlive, xetexlive-more]


    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{ secrets.password }} | docker login -u ${{ secrets.username }} --password-stdin
        docker build . --file ${{ matrix.image }}/Dockerfile --tag ${{ secrets.username }}/${{ matrix.image }}:latest
        docker push ${{ secrets.username }}/${{ matrix.image }}:latest
